# -*- coding: utf-8 -*-
"""DBSCAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfsHiWiU4TOAi_DHClJv9x6G7PrCkIzO
"""

from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons,make_circles
import matplotlib.pyplot as plt

x,_ = make_moons(n_samples=300,noise=0.05,random_state=12)

x

plt.scatter(x[:,0],x[:,1])

# DBSCAN

db = DBSCAN(eps=0.2,min_samples=5)

labels = db.fit_predict(x)

plt.scatter(x[:,0],x[:,1],c=labels)
plt.title("DBSCAN Clusterring")
plt.xlabel("x")
plt.ylabel("y")
plt.show()



# K Means

from sklearn.cluster import KMeans

km = KMeans(n_clusters=2)
y_pred = km.fit_predict(x)

y_pred

# Plot
plt.scatter(x[:, 0], x[:, 1], c=y_pred)
plt.scatter(km.cluster_centers_[:, 0], km.cluster_centers_[:, 1],s=200, c='red', marker='X', label='Centroids')
plt.title('K-Means Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.show()

x,_ = make_circles(n_samples=500,noise=0.05,random_state=12,factor=0.5)
x

plt.scatter(x[:,0],x[:,1])

db = DBSCAN(eps=0.1,min_samples=5)
labels = db.fit_predict(x)

plt.scatter(x[:,0],x[:,1],c=labels)

labels

(labels == -1).sum()

# K Means

km = KMeans(n_clusters=2)
y_pred = km.fit_predict(x)

plt.scatter(x[:,0],x[:,1],c=y_pred)

