# -*- coding: utf-8 -*-
"""DL-NLP_Intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1YgEzhLEFSYLKcSSTRzLLXEtesrWgfT
"""

pip install diffusers --upgrade