# -*- coding: utf-8 -*-
"""Embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ptcz9OGUw-O1bBDq-DtkfG_b8Z8jxir
"""

!pip install --force-reinstall --no-cache-dir numpy gensim scipy

!pip show gensim

!pip install --upgrade gensim

import gensim.downloader as api

info = api.info()
for model_name, model_data in sorted(info['models'].items()):
    num_records = model_data.get('num_records', -1)
    description = model_data.get('description', '')[:40] + '...'
    print(f'{model_name} ({num_records} records): {description}')

wv = api.load('word2vec-google-news-300')

wv.most_similar("tea")

glove = api.load('glove-twitter-50')

glove.most_similar("tea")

wv.distance('tea','milk')

glove.distance('tea','pea')

wv.distance('tea','pea')

wv.most_similar_cosmul(positive=['King','Women'],negative=['man'])

