# -*- coding: utf-8 -*-
"""Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcN4T19miWDfOJWzn4YoK5hogniReegH
"""

from sklearn.preprocessing import LabelEncoder

import pandas as pd

df = pd.DataFrame({'color':['Red','Blue','Green','Blue','Red'],'Target':[1,0,1,0,1]})
df

le = LabelEncoder()

# Label Encoding
df['color'] = le.fit_transform(df['color'])
df

# One hot Encoding
df_ohe = pd.get_dummies(df['color'],prefix='color')
df_ohe

pd.concat([df,df_ohe],axis=1)

# Target Encoding
df = pd.DataFrame({'color':['Blue','Red','Green','Blue','Green','Green','Blue'],'Target':[1,0,1,0,1,0,0]})
df

target = df.groupby('color')['Target'].mean()
target

df['color'] = df['color'].map(target)

df

