# -*- coding: utf-8 -*-
"""Hirarchichal_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBnwhS1G4-TOV-bhfGSDYu4Yx_tZA7GD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram,linkage

x = np.array([[1,2],[2,3],[3,4],[8,7],[8,8],[25,80]])

linked = linkage(x,method='ward')

plt.figure(figsize=(8,5))
dendrogram(linked,orientation='top',labels=np.arange(1,len(x)+1),distance_sort='desending',show_leaf_counts=True)
plt.title("Dendrogram")
plt.show

from sklearn.cluster import AgglomerativeClustering

x = np.array([[1,2],[2,3],[3,4],[8,7],[8,8],[25,80]])

model = AgglomerativeClustering(2)
model.fit(x)
print("Clusters : ",model)

