# -*- coding: utf-8 -*-
"""Mall_Customer_KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2K5GzJLppZ0eSuWHCzomEGbc_vCqc5Z
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/content/Mall_Customers.csv")
df

df = df.rename(columns={"Annual Income (k$)":"Annual Income"})
df = df.rename(columns={"Spending Score (1-100)":"Spending Score"})

scaler = MinMaxScaler()

df['Age'] = scaler.fit_transform(df[['Age']])
df['Annual Income'] = scaler.fit_transform(df[['Annual Income']])
df['Spending Score'] = scaler.fit_transform(df[['Spending Score']])

le = LabelEncoder()

df['Genre'] = le.fit_transform(df['Genre'])

plt.scatter(df['Annual Income'],df['Spending Score'])

df

df.columns

x = df[['Annual Income', 'Spending Score']]

km = KMeans(n_clusters = 5)

y_pred = km.fit_predict(x)
y_pred

df['Cluster'] = y_pred

df

km.cluster_centers_

df0 = df[df['Cluster'] == 0]
df1 = df[df['Cluster'] == 1]
df2 = df[df['Cluster'] == 2]
df3 = df[df['Cluster'] == 3]
df4 = df[df['Cluster'] == 4]

plt.scatter(df0['Annual Income'],df0['Spending Score'],color = 'Blue')
plt.scatter(df1['Annual Income'],df1['Spending Score'],color = 'red')
plt.scatter(df2['Annual Income'],df2['Spending Score'],color = 'Green')
plt.scatter(df3['Annual Income'],df3['Spending Score'],color = 'orange')
plt.scatter(df4['Annual Income'],df4['Spending Score'],color = 'purple')

plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color = 'black',marker = '*')

