# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oiv9sJMQVVkwhIO_HE371Ygk11-8q9n9
"""

import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [2,5,6,7,8]

plt.plot(x,y, marker ='o',label = "Info",color = "black",linestyle = "--")
plt.grid()
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Plot")
plt.legend()
plt.show()

x = [3,3,3,4,5]
y = [3,5,6,7,8]

plt.scatter(x,y, marker ='+')

x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

plt.scatter(x,y,marker = "+", s = 100,color = "red", label = "Data Points")
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Scatter Plot Example')
plt.legend()
plt.show()

import numpy as np

x = np.random.randint(1,100,size = (100))
y = np.random.randint(1,100,size = (100))

plt.scatter(x,y,marker = "+", s = 100,color = "red", label = "Data Points")
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Scatter Plot Example')
plt.legend()
plt.show()

x = [1,2,3,4,5]
y = [3,5,6,7,8]

plt.bar(x,y)

items = ["Vada pav","Panipuri","Samosa","Kachori"]
price = [25,40,20,20]

plt.bar(items,price,color = 'gray')
plt.xlabel("Items")
plt.ylabel("Price")
plt.title("Menu Card")
plt.show()

x = [1,1,2,2,5]
y = [1,2,2,1,5]

plt.scatter(x,y, marker ='+')

import matplotlib.pyplot as plt
import numpy as np

# Generate random data
data = np.random.normal(100, 20, 1000)

plt.hist(data,color = "green",edgecolor = "black",bins = 20)
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram Example')
plt.show()

labels = ["A","B","C","D"]
values = [20,30,40,10]
colors = ["lightcoral","lightgray","lightgreen","gold"]

plt.pie(values,labels = labels, colors = colors, autopct = "%1.1f%%", startangle=120)
plt.title('Pie Chart Example')
plt.show()

