# -*- coding: utf-8 -*-
"""ML_flow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXoaxZdcAoCAXFzTzk8CK3eZh2XrtD4r
"""

# Prepro
#training/test
#evaluate


import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report , accuracy_score

df = pd.read_csv("music.csv")
df

#x and y

x =  df[['age','gender']]
y = df['genre']



x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=13)
x_train

# call the model

chintu = KNeighborsClassifier(7)

#Training

chintu.fit(x_train,y_train)

# Testing

y_pred = chintu.predict(x_test)
y_pred

y_test

3/4

print(classification_report(y_test,y_pred))

chintu

df = pd.read_csv('/content/diabetes.csv')
df

df.columns

x = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]

y = df['Outcome']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=17)

chintu.fit(x_train,y_train)

y_pred = chintu.predict(x_test)

print(classification_report(y_test,y_pred))

for i in range(100):
  x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=i)
  chintu.fit(x_train,y_train)
  y_pred = chintu.predict(x_test)
  print(f'at random state {i}, the accuracy is : {accuracy_score(y_test,y_pred)}')

