# -*- coding: utf-8 -*-
"""NLP_tokenization_stopwords B3 1230 batch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TU7TTrwpCdhPbn0H_KoahfDjLwAlPutM
"""

sen = "class ka last 10 mins madhe mala remind kara, ki ,feedback ghyaya cha aahe"

sen.split()

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


nltk.download('punkt_tab')

nltk.download('stopwords')

t_sen = word_tokenize(sen)
t_sen

print(sen.split())

print(t_sen)

#=== Stop words ====

text = "This is an example of a sentence showing how to remove the stopwords using NLTK"

tokens = word_tokenize(text)


stop_words =  set(stopwords.words('english'))

[word for word in tokens if word.lower() not in stop_words]

len(tokens)

web_text = """ To create a website, start by defining your website’s purpose and choosing a platform.
Wix is a beginner-friendly website builder that makes setup fast and easy. Next, register your domain,
secure hosting and design your site using a template customized to your brand.
 Add content and functionality, test everything across devices and finally, launch and promote your website
  to attract visitors and keep it up to date. """

# tokenize

web_tokenize = word_tokenize(web_text)
len(web_tokenize)

#  remove the stopwords

web_stopwords =  [word for word in web_tokenize if word.lower() not in stop_words]
len(web_stopwords)

# ===== From the blog



import string
punctuations = string.punctuation
def removing_punctuations(text,punctuations):
    for punc in list(punctuations):
        if punc in text:
            text = text.replace(punc, ' ')
    return text

string.punctuation

print(web_text)

p_text  = """  $$$$$$ aloo wada &&&& ###### Pani puri """

removing_punctuations(p_text,punctuations)





import re

def text_to_procedure(text):
    # Define basic actions and patterns (could be expanded)
    actions = {
        'add': r'\badd\b.*?(?=\.|,| and )',
        'stir': r'\bstir\b.*?(?=\.|,| and )',
        'concentrate': r'\b(evaporate|concentrate)\b.*?(?=\.|,| and )',
        'extract': r'\bextract\b.*?(?=\.|,| and )',
        'wash': r'\bwash\b.*?(?=\.|,| and )',
        'dry': r'\bdry\b.*?(?=\.|,| and )',
        'purify': r'\bpurif\w*\b.*?(?=\.|,| and )',
        'yield': r'\byield\b.*?(?=\.|,| and )'
    }

    text = text.lower()
    steps = []
    for action, pattern in actions.items():
        matches = re.findall(pattern, text)
        for match in matches:
            steps.append((action.upper(), match.strip('. ')))
    if not steps:
        # fallback: split by sentences as naive steps
        steps = [(f'STEP {i+1}', s.strip()) for i, s in enumerate(re.split(r'\.|\n', text)) if s.strip()]
    return steps

# Example usage
input_text = """ 1-fluorophenyl)ethenone (10 g, 1.0 eq) was taken in methanol (300 ml) and hydroxyl amine hydrochloride (7.54 g, 1.8 eq) was added. Pyridine (33.45 g, 2 eq) was added drop wise at 25° C. Reaction mixture was stirred at 50° C. for 2 hr...."""
steps = text_to_procedure(input_text)

for step in steps:
    print(f"{step[0]}: {step[1]}")

input_text = """ 1-fluorophenyl)ethanone oxime (0.3 g, 3 eq) was taken in dimethyl formamide (DMF, 5 ml) and Cs 2CO 3 (3.27 g, 2.0 eq) was added. The reaction mixture was stirred for 30 minutes at room temperature (RT; at about 25° C.) and then added methyl (2E)-2-[2-(bromomethyl)-3-methyl-phenyl]-2-methoxyimino-acetate (0.6 g, 3.02 eq). The reaction mixture was stirred at RT for 32 hr and monitored by TLC and LCMS. Reaction was quenched with water (45 ml) and the product was extracted in ethyl acetate (3 x 35 ml). The combined organic layer was washed with brine (50 ml), dried over sodium sulphate and concentrated under vacuum. Crude material was purified by flash chromatography. Pure compound was eluted by using 35-20% EtOAc in heptane. Evaporation of solvent afforded an off-white solid title compound (0.328 g, 45% yield). 1H NMR (300 MHz, DMSO-d6): δ 7.56 - 7.36 (m, 2H), 7.33 - 7.32 (m, 4H), 7.03 (dd, J = 6.2, 2.8 Hz, 3H), 5.00 (s, 2H), 3.93 (s, 3H), 3.64 (s, 3H), 2.42 (s, 3H), 2.08 (d, J = 2.5 Hz, 3H). """

steps = text_to_procedure(input_text)

for step in steps:
    print(f"{step[0]}: {step[1]}")

import re

def extract_procedure(text):
    # Normalize spaces and lower the case for easier parsing
    text = text.replace('\n', ' ').strip()

    steps = []

    # Patterns for different actions
    add_pattern = re.compile(r'(?:was )?added(?: drop wise)?(?: at \d+°? ?C)?[^\.\,]*')
    stir_pattern = re.compile(r'stirred(?: for [^\.]+)?')
    concentrate_pattern = re.compile(r'(?:evaporated|concentrated) under vacuum')
    quench_pattern = re.compile(r'reaction was quenched with [^\.\,]+')
    extract_pattern = re.compile(r'extracted (?:with )?([^\.,]+)(?: \(\d+ ml\))?(?:,? \d+ x \d+ ml)?')
    wash_pattern = re.compile(r'washed with [^\.\,]+')
    dry_pattern = re.compile(r'dried over [^\.\,]+')
    purify_pattern = re.compile(r'purified by [^\.\,]+')
    yield_pattern = re.compile(r'afforded(?: an)? (.+) \(([\d\.]+ g), ([\d]+)% yield\)')

    # Extract ADD steps based on 'added' phrases
    add_matches = re.findall(add_pattern, text)
    for add in add_matches:
        add = add.strip()
        # Refine to include compound and quantity
        # Find preceding compound and quantity before 'added' phrase
        pre_add = re.findall(r'(\S.*?\)) ' + re.escape(add), text)
        if pre_add:
            compound = pre_add[0]
            steps.append(f"ADD {compound}")

    # STIR steps
    stir_matches = re.findall(stir_pattern, text)
    for stir in stir_matches:
        steps.append(f"STIR {stir[len('stirred'):].strip()}")

    # CONCENTRATE steps
    if re.search(concentrate_pattern, text):
        steps.append("CONCENTRATE")

    # QUENCH step
    quench_match = re.search(quench_pattern, text)
    if quench_match:
        quencher = quench_match.group(0).replace('reaction was quenched with ', '').strip()
        steps.append(f"QUENCH with {quencher}")

    # EXTRACT steps
    extract_matches = re.findall(r'extracted in ([^\(]+)(?: \((\d+ ml)\))?', text)
    if extract_matches:
        for ext_solvent, vol in extract_matches:
            vol_str = f"({vol})" if vol else ""
            steps.append(f"EXTRACT with {ext_solvent.strip()} {vol_str} 3 x")

    # WASH steps
    wash_match = re.search(wash_pattern, text)
    if wash_match:
        wash_what = wash_match.group(0).replace('washed with ', '').strip()
        steps.append(f"WASH with {wash_what}")

    # DRY step
    dry_match = re.search(dry_pattern, text)
    if dry_match:
        dry_what = dry_match.group(0).replace('dried over ', '').strip()
        steps.append(f"DRYSOLUTION over {dry_what}")

    # Concentrate again check
    if re.search(concentrate_pattern, text):
        steps.append("CONCENTRATE")

    # PURIFY steps
    purify_match = re.search(purify_pattern, text)
    if purify_match:
        steps.append("PURIFY")
        # Occasionally purification repeated twice
        if text.lower().count('purified by') > 1:
            steps.append("PURIFY")

    # YIELD
    yield_match = re.search(yield_pattern, text)
    if yield_match:
        compound_name = yield_match.group(1)
        compound_wt = yield_match.group(2)
        compound_yield = yield_match.group(3)
        steps.append(f"YIELD {compound_name} ({compound_wt} g, {compound_yield}% yield)")

    # Remove possible duplicates and preserve order
    seen = set()
    final_steps = []
    for step in steps:
        if step not in seen:
            final_steps.append(step)
            seen.add(step)

    return final_steps


# Example input text
# input_text = """ 1-fluorophenyl)ethanone oxime (0.3 g, 3 eq) was taken in dimethyl formamide (DMF, 5 ml) and Cs 2CO 3 (3.27 g, 2.0 eq) was added. The reaction mixture was stirred for 30 minutes at room temperature (RT; at about 25° C.) and then added methyl (2E)-2-[2-(bromomethyl)-3-methyl-phenyl]-2-methoxyimino-acetate (0.6 g, 3.02 eq). The reaction mixture was stirred at RT for 32 hr and monitored by TLC and LCMS. Reaction was quenched with water (45 ml) and the product was extracted in ethyl acetate (3 x 35 ml). The combined organic layer was washed with brine (50 ml), dried over sodium sulphate and concentrated under vacuum. Crude material was purified by flash chromatography. Pure compound was eluted by using 35-20% EtOAc in heptane. Evaporation of solvent afforded an off-white solid title compound (0.328 g, 45% yield)."""


input_text = """ 1-fluorophenyl)ethenone (10 g, 1.0 eq) was taken in methanol (300 ml) and hydroxyl amine hydrochloride (7.54 g, 1.8 eq) was added. Pyridine (33.45 g, 2 eq) was added drop wise at 25° C. Reaction mixture was stirred at 50° C. for 2 hr. Reaction was monitored using LCMS & TLC. Methanol was evaporated under vacuum. Crude mass was diluted with water (200 ml) and it was extracted with ethyl acetate (3 x 100 ml). Combined organic layer was again washed with water and brine. Organic layer was dried over sodium sulphate and concentrated under vacuum. Crude compound was purified by flash column chromatography. Pure compound was eluted with 0% to 20% ethyl acetate (EtOAc) in heptane. Evaporation of solvent afforded 8 g title compound as white solid (Yield 72%). 1H NMR 300 MHz, DMSO-d6: δ 11.4 (s ,1 H), 7.46-7.41 (m, 2 H), 7.27-7.23 (m, 2H), 2.14 (s, 3H). """

# Run extraction
output_steps = extract_procedure(input_text)

# Display output similar to IBM RXN style
for step in output_steps:
    print(step)

RXN_API = "apk-7b6b849b4c0e86cc3f57ac720f496310c2719b382e94f3ab5268d55967ed580f"

from rxn4chemistry.core import RXN4ChemistryWrapper

# Initialize the wrapper with your API key
rxn4chemistry_wrapper = RXN4ChemistryWrapper(api_key=RXN_API)

reaction_paragraph = """
1-fluorophenyl)ethanone oxime (0.3 g, 3 eq) was taken in dimethyl formamide (DMF, 5 ml) and Cs2CO3 (3.27 g, 2.0 eq) was added. The reaction mixture was stirred for 30 minutes at room temperature (RT; at about 25° C.) and then added methyl (2E)-2-[2-(bromomethyl)-3-methyl-phenyl]-2-methoxyimino-acetate (0.6 g, 3.02 eq). The reaction mixture was stirred at RT for 32 hr and monitored by TLC and LCMS. Reaction was quenched with water (45 ml) and the product was extracted in ethyl acetate (3 x 35 ml). The combined organic layer was washed with brine (50 ml), dried over sodium sulphate and concentrated under vacuum. Crude material was purified by flash chromatography. Pure compound was eluted by using 35-20% EtOAc in heptane. Evaporation of solvent afforded an off-white solid title compound (0.328 g, 45% yield).
"""

# Call the paragraph to actions API
result = rxn4chemistry_wrapper.paragraph_to_actions(paragraph=reaction_paragraph)

# Extracted list of actions
actions_list = result.get('actions', [])

# Print actions in a readable format
for action in actions_list:
    print(action)

! pip install rxn4chemistry

