# -*- coding: utf-8 -*-
"""pickle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKYnqzokVphBIeILjdJHpaAEME86lqfx
"""

import pickle
with open("/content/samosa.pkl",'rb') as f:
  loaded_file = pickle.load(f)

loaded_file

