# -*- coding: utf-8 -*-
"""Practice5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJiapIUI4YxK6ZP3_fF4JprwMKgL1DZr
"""

# K_means

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv("/content/income.csv")
df

# Rename 'Income($)' to 'Income'
df = df.rename(columns={'Income($)': 'Income'})

plt.scatter(df['Age'],df["Income"])

km = KMeans(n_clusters=3)

scaler = MinMaxScaler()

df['Income'] = scaler.fit_transform(df[['Income']])
df['Age'] = scaler.fit_transform(df[['Age']])
df

x = df[['Age','Income']]

y_pred = km.fit_predict(x)

df['Cluster'] = y_pred

df

km.cluster_centers_

df1 = df[df['Cluster'] == 0]
df2 = df[df['Cluster'] == 1]
df3 = df[df['Cluster'] == 2]

plt.scatter(df1['Age'],df1['Income'],color = 'red')
plt.scatter(df2['Age'],df2['Income'],color = 'Green')
plt.scatter(df3['Age'],df3['Income'],color = 'Blue')
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='black',marker='*')

plt.scatter(df['Age'],df['Income'],c=km.labels_)
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color = 'black',marker = '*')





from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

x,_ = make_moons(n_samples=400,noise=0.05,random_state=12)

x

plt.scatter(x[:,0],x[:,1])

db = DBSCAN(eps = 0.2,min_samples=5)

labels = db.fit_predict(x)

plt.scatter(x[:,0],x[:,1],c=labels)
plt.title("DBSCAN Clusterring")
plt.xlabel("x")
plt.ylabel("y")
plt.show()



km = KMeans(n_clusters=2)

labels = km.fit_predict(x)

plt.scatter(x[:,0],x[:,1],c=labels)
plt.scatter(km.cluster_centers_[:, 0], km.cluster_centers_[:, 1],s=200, c='red', marker='X', label='Centroids')
plt.title("K Means")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

