# -*- coding: utf-8 -*-
"""Scalers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Qf5ArKR0BMWxwgDhFQQIofu-Q_LsIuC
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import RobustScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

df = pd.DataFrame({"Salary":[70000,60000,52000,45000]})
df

# MinMaxScaler

scaler =MinMaxScaler()
scaler.fit_transform(df[['Salary']])

# StandardScaler

scaler =StandardScaler()
scaler.fit_transform(df[['Salary']])

# MaxAbsScaler

scaler =MaxAbsScaler()
scaler.fit_transform(df[['Salary']])

# RobustScaler

scaler =RobustScaler()
scaler.fit_transform(df[['Salary']])







df = pd.read_csv("/content/diabetes.csv")
df

df.columns

scaler = MinMaxScaler()
for col in df.columns:
  df[col] = scaler.fit_transform(df[[col]])

df

x = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]
y = df['Outcome']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=32)

knn = KNeighborsClassifier()

knn.fit(x_train,y_train)

pred = knn.predict(x_test)

print(classification_report(y_test,pred))

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(x='Age',y='BloodPressure',data = df)

